'use client';

import { useMemo, useState, useTransition } from 'react';
import { useRouter } from '@/i18n/navigation';
import { Card, CardBody, CardHeader } from '@/components/ui/Card';
import { updateRefundTiersAction } from '@/features/admin/settings-actions';
import { formatRefundTiers, type RefundTier } from '@/lib/refund-policy';

interface Props {
  initialTiers: RefundTier[];
}

interface Row {
  hours: string;
  percent: string;
}

/** "= 7 days" / "= 2d 12h" helper shown under each hours input. */
function hoursHint(hoursStr: string): string {
  const h = Number(hoursStr);
  if (!Number.isFinite(h) || h < 0 || !Number.isInteger(h)) return '';
  if (h === 0) return '= last-minute / no-show floor';
  if (h % 24 === 0) return `= ${h / 24} day${h / 24 === 1 ? '' : 's'}`;
  const d = Math.floor(h / 24);
  const rem = h % 24;
  return d > 0 ? `= ${d}d ${rem}h` : `= ${rem}h`;
}

/**
 * Editable schedule of refund bands, saved separately from the free-text policy.
 * The enforced numbers live here; the preview below is generated by the SAME
 * `formatRefundTiers` used on the customer side, so what staff see is exactly
 * what guests see and what the system charges.
 */
export function RefundTiersForm({ initialTiers }: Props) {
  const [isPending, startTransition] = useTransition();
  const router = useRouter();
  const [rows, setRows] = useState<Row[]>(
    (initialTiers.length ? initialTiers : [{ minHoursBeforeStart: 0, refundPercent: 0 }]).map((t) => ({
      hours: String(t.minHoursBeforeStart),
      percent: String(t.refundPercent),
    })),
  );

  const parsed = useMemo(
    () => rows.map((r) => ({ minHoursBeforeStart: Number(r.hours), refundPercent: Number(r.percent) })),
    [rows],
  );

  const error = useMemo<string | null>(() => {
    for (const t of parsed) {
      if (!Number.isInteger(t.minHoursBeforeStart) || t.minHoursBeforeStart < 0)
        return 'Every "hours before" must be a whole number ≥ 0.';
      if (!Number.isInteger(t.refundPercent) || t.refundPercent < 0 || t.refundPercent > 100)
        return 'Every refund % must be a whole number between 0 and 100.';
    }
    const seen = new Set<number>();
    for (const t of parsed) {
      if (seen.has(t.minHoursBeforeStart)) return 'Two tiers use the same "hours before" threshold.';
      seen.add(t.minHoursBeforeStart);
    }
    const sorted = [...parsed].sort((a, b) => b.minHoursBeforeStart - a.minHoursBeforeStart);
    for (let i = 1; i < sorted.length; i++) {
      if (sorted[i]!.refundPercent > sorted[i - 1]!.refundPercent)
        return 'Refund % may not increase as the cancellation gets closer to the visit.';
    }
    return null;
  }, [parsed]);

  const preview = useMemo(() => (error ? [] : formatRefundTiers(parsed, 'en')), [parsed, error]);

  function setRow(i: number, patch: Partial<Row>) {
    setRows((prev) => prev.map((r, idx) => (idx === i ? { ...r, ...patch } : r)));
  }
  function addRow() {
    setRows((prev) => [...prev, { hours: '0', percent: '0' }]);
  }
  function removeRow(i: number) {
    setRows((prev) => (prev.length <= 1 ? prev : prev.filter((_, idx) => idx !== i)));
  }

  function handleSubmit(e: React.FormEvent<HTMLFormElement>) {
    e.preventDefault();
    if (error) return;
    startTransition(async () => {
      const res = await updateRefundTiersAction(parsed);
      if (res.ok) {
        router.refresh();
      } else {
        alert(`Failed to save refund tiers (${res.code}). Check the console.`);
      }
    });
  }

  return (
    <form onSubmit={handleSubmit} className="space-y-6">
      <Card>
        <CardHeader>
          <h2 className="font-display text-lg font-semibold text-gold-600">Refund Schedule (enforced)</h2>
          <p className="text-sm text-muted-foreground">
            These bands are what the system actually refunds when a booking is cancelled, based on how
            many hours before the visit day it happens. Saving forces all users to re-accept the policy.
          </p>
        </CardHeader>
        <CardBody className="space-y-4">
          <div className="space-y-3">
            <div className="grid grid-cols-[1fr_1fr_auto] gap-3 text-xs font-semibold uppercase tracking-wide text-muted-foreground">
              <span>Hours before visit (≥)</span>
              <span>Refund %</span>
              <span className="sr-only">Remove</span>
            </div>
            {rows.map((row, i) => (
              <div key={i} className="grid grid-cols-[1fr_1fr_auto] items-start gap-3">
                <div>
                  <input
                    type="number"
                    min={0}
                    step={1}
                    inputMode="numeric"
                    value={row.hours}
                    onChange={(e) => setRow(i, { hours: e.target.value })}
                    className="h-11 w-full rounded-xl border border-border/40 bg-input px-3 text-sm text-foreground focus:outline-none focus:ring-2 focus:ring-accent"
                  />
                  <span className="mt-1 block text-xs text-muted-foreground">{hoursHint(row.hours)}</span>
                </div>
                <input
                  type="number"
                  min={0}
                  max={100}
                  step={1}
                  inputMode="numeric"
                  value={row.percent}
                  onChange={(e) => setRow(i, { percent: e.target.value })}
                  className="h-11 w-full rounded-xl border border-border/40 bg-input px-3 text-sm text-foreground focus:outline-none focus:ring-2 focus:ring-accent"
                />
                <button
                  type="button"
                  onClick={() => removeRow(i)}
                  disabled={rows.length <= 1}
                  className="h-11 rounded-xl border border-border/40 px-3 text-sm text-muted-foreground transition-colors hover:bg-muted disabled:opacity-40"
                  aria-label="Remove tier"
                >
                  ✕
                </button>
              </div>
            ))}
          </div>

          <button
            type="button"
            onClick={addRow}
            className="h-10 rounded-xl border border-dashed border-border px-4 text-sm font-medium text-foreground transition-colors hover:bg-muted"
          >
            + Add tier
          </button>

          {error ? (
            <p className="rounded-xl bg-destructive/10 px-4 py-3 text-sm text-destructive">{error}</p>
          ) : (
            <div className="rounded-xl bg-muted/40 px-4 py-3">
              <p className="mb-2 text-xs font-semibold uppercase tracking-wide text-muted-foreground">
                What customers will see
              </p>
              <ul className="space-y-1 text-sm text-foreground">
                {preview.map((line, i) => (
                  <li key={i}>• {line}</li>
                ))}
              </ul>
            </div>
          )}
        </CardBody>
      </Card>

      <div className="flex justify-end">
        <button
          type="submit"
          disabled={isPending || !!error}
          className="h-11 rounded-xl bg-primary px-8 text-sm font-bold text-primary-foreground transition-opacity hover:opacity-90 disabled:opacity-50"
        >
          {isPending ? 'Saving...' : 'Save Refund Schedule'}
        </button>
      </div>
    </form>
  );
}
